spring.datasource.url=jdbc:mysql://sakura.proxy.rlwy.net:31561/user-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=wwpgdgRKKXyvWUwXLRuDjRHCQxvGzRBl
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
jwt.secret.key: secret_secret_secret_secret_secret_secret_secret_secret_secret_secret
